"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Send } from "lucide-react";
import "../../portal.css";
import "../parent.css";
import "./request.css";

const fields=["学员年级","性别","科目","当前情况","辅导目标","所在区域","地址","每周次数","单次时长","可上课时间","期望老师类型","老师性别要求","其他要求","预算","微信","手机号"];
export default function ParentRequest(){const [done,setDone]=useState(false);const [saving,setSaving]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const form=new FormData(e.currentTarget);const payload=Object.fromEntries(fields.map((field)=>[field,String(form.get(field)||"").trim()]));const record={...payload,id:`family-${Date.now()}`,source_channel:"owned",public_pool:"owned",state:"pending_review",created_at:new Date().toISOString()};try{const old=JSON.parse(localStorage.getItem("parent-requests-v1")||"[]");localStorage.setItem("parent-requests-v1",JSON.stringify([record,...old]));setDone(true)}catch{alert("浏览器本地存储不可用，请检查浏览器设置。")};setSaving(false)}return <main className="portal-shell request-shell"><header className="portal-header"><Link className="portal-brand" href="/parent"><span>家</span>提交辅导需求</Link><Link className="portal-back" href="/parent"><ArrowLeft size={15}/> 返回家长端</Link></header>{done?<section className="request-done"><CheckCircle2 size={46}/><h1>需求已提交，等待运营审核</h1><p>需求已标记为「待审核」，不会直接展示给老师。演示版本将资料保存在当前浏览器。</p><div><Link className="parent-primary" href="/">返回首页</Link><Link className="request-secondary" href="/manage/review">内部审核页</Link></div></section>:<><div className="request-heading"><span className="portal-kicker">FAMILY REQUEST</span><h1>我要找老师</h1><p>请尽量填写完整，运营审核通过后会根据区域、科目和时间协助匹配。</p><span className="private-note">🔒 微信和手机号只用于内部联络，不会公开给老师</span></div><form className="request-form" onSubmit={submit}><div className="request-grid">
{fields.map((field)=>{const long=["当前情况","辅导目标","地址","可上课时间","老师性别要求","其他要求"].includes(field);const required=!['其他要求'].includes(field);const options:Record<string,string[]>={"学员年级":["幼儿园","一年级","二年级","三年级","四年级","五年级","六年级","初一","初二","初三","高一","高二","高三","其他"],"性别":["男","女","不限制"],"所在区域":["天河区","越秀区","荔湾区","海珠区","番禺区","花都区","黄埔区","增城区","白云区","其他"],"期望老师类型":["大学生","专职老师","均可"],"每周次数":["1次","2次","3次","4次","5次","协商"],"单次时长":["1小时","1.5小时","2小时","2.5小时","3小时","协商"]};return <label key={field} className={`request-field ${long?"request-wide":""}`}>{field}{required&&<i> *</i>}{options[field]?<select name={field} required={required} defaultValue=""><option value="" disabled>请选择</option>{options[field].map(x=><option key={x}>{x}</option>)}</select>:long?<textarea name={field} required={required} rows={field==="地址"?2:3} placeholder={`请填写${field}`}/>:<input name={field} required={required} placeholder={field==="预算"?"例如：100–150元/小时":`请填写${field}`} />}</label>})}</div><div className="request-submit-row"><span>提交后由运营人员审核；不会自动公开订单。</span><button className="parent-primary" disabled={saving}>{saving?"提交中…":"提交需求"}<Send size={15}/></button></div></form></>}</main>}
